# 预备知识

## 数据操作

### 创建tensor

In [1]:
import torch

In [15]:
import numpy as np

In [2]:
# 未初始化 tensor
torch.empty(5,3)

tensor([[ 0.0000e+00,  0.0000e+00,  2.4153e-33],
        [ 1.4013e-45, -7.7987e-36,  4.5754e-41],
        [-1.0649e-37,  4.5754e-41,  2.4204e-33],
        [ 1.4013e-45,  2.4107e-33,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [3]:
# 初始化 
torch.randn(5,3)

tensor([[-0.1113, -0.0239, -1.4283],
        [ 0.8953, -0.1287,  0.9335],
        [-0.9187,  0.5247, -0.9564],
        [-0.9037,  1.2366, -0.1941],
        [ 0.6389, -1.1047, -0.3533]])

In [4]:
# 全零
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# 直接创建
x = torch.Tensor([5.4,3])

In [7]:
x

tensor([5.4000, 3.0000])

In [8]:
x = x.new_ones(5,3,dtype=torch.float64)

In [9]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
x = torch.randn_like(x,dtype=torch.float)

In [11]:
x

tensor([[ 0.2558, -2.5110,  0.9224],
        [ 0.2972,  0.1293, -0.3202],
        [ 0.3940,  0.7585,  1.0187],
        [ 0.3075,  0.9384, -0.6080],
        [ 0.8044, -0.6716,  0.8548]])

In [12]:
# 获取形状
x.size()

torch.Size([5, 3])

In [13]:
x.shape

torch.Size([5, 3])

In [16]:
# 根据numpy
torch.tensor(np.array([[2,4],[4,5]]),dtype=torch.float)

tensor([[2., 4.],
        [4., 5.]])

In [18]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [25]:
x  = torch.arange(1,12,2).view(2,3)

In [26]:
x.size()

torch.Size([2, 3])

In [34]:
torch.linspace(1,10,10,dtype=float)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)

In [39]:
torch.normal(0,1,(2,2))

tensor([[1.8975, 0.6649],
        [0.0799, 0.1688]])

AttributeError: module 'torch' has no attribute 'uniform'

### 操作

In [ ]:
# 算数操作

In [41]:

# 加法形式1
x = torch.randn(5,3)

In [42]:
x

tensor([[ 0.7086, -0.7837,  1.3360],
        [ 1.1197,  1.9167,  0.8196],
        [ 0.3701, -1.4880,  0.0214],
        [-1.7331, -0.2454, -1.4524],
        [-1.4059,  0.2681,  0.5895]])

In [43]:
y = torch.rand(5,3)

In [44]:
y

tensor([[0.3692, 0.2018, 0.7290],
        [0.3640, 0.4273, 0.0786],
        [0.2943, 0.6365, 0.5373],
        [0.6194, 0.7344, 0.9623],
        [0.0420, 0.1156, 0.6017]])

In [45]:
x + y

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [46]:
# 加法形式2
torch.add(x,y)

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [47]:
# 可以指定输出
result = torch.empty(5,3)
torch.add(x,y,out=result)

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [48]:
result

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [49]:
# 加法形式3
y.add_(x)

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [50]:
y

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [51]:
x

tensor([[ 0.7086, -0.7837,  1.3360],
        [ 1.1197,  1.9167,  0.8196],
        [ 0.3701, -1.4880,  0.0214],
        [-1.7331, -0.2454, -1.4524],
        [-1.4059,  0.2681,  0.5895]])

In [52]:
x.t_()

tensor([[ 0.7086,  1.1197,  0.3701, -1.7331, -1.4059],
        [-0.7837,  1.9167, -1.4880, -0.2454,  0.2681],
        [ 1.3360,  0.8196,  0.0214, -1.4524,  0.5895]])

In [54]:
x.t_()

tensor([[ 0.7086, -0.7837,  1.3360],
        [ 1.1197,  1.9167,  0.8196],
        [ 0.3701, -1.4880,  0.0214],
        [-1.7331, -0.2454, -1.4524],
        [-1.4059,  0.2681,  0.5895]])

In [55]:
x.copy_(y)

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [56]:
x

tensor([[ 1.0778, -0.5819,  2.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [ ]:
# 索引
# 索引出来的结果与原数据共享内存，修改一个 另一个也随着变

In [57]:
y = x[0,:]

In [58]:
y

tensor([ 1.0778, -0.5819,  2.0650])

In [59]:
y +=1

In [60]:
y

tensor([2.0778, 0.4181, 3.0650])

In [61]:
x[0,:]

tensor([2.0778, 0.4181, 3.0650])

In [62]:
x

tensor([[ 2.0778,  0.4181,  3.0650],
        [ 1.4837,  2.3440,  0.8982],
        [ 0.6643, -0.8515,  0.5587],
        [-1.1137,  0.4890, -0.4901],
        [-1.3639,  0.3837,  1.1912]])

In [68]:
torch.index_select(x,1,torch.LongTensor([0.,0.,1.]))

tensor([[ 2.0778,  2.0778,  0.4181],
        [ 1.4837,  1.4837,  2.3440],
        [ 0.6643,  0.6643, -0.8515],
        [-1.1137, -1.1137,  0.4890],
        [-1.3639, -1.3639,  0.3837]])

In [69]:
# torch.gather(x,0,torch.LongTensor([1.,1.,0.]))

RuntimeError: Index tensor must have the same number of dimensions as input tensor

In [70]:
# 改变形状
y = x.view(15)

In [71]:
y

tensor([ 2.0778,  0.4181,  3.0650,  1.4837,  2.3440,  0.8982,  0.6643, -0.8515,
         0.5587, -1.1137,  0.4890, -0.4901, -1.3639,  0.3837,  1.1912])

In [73]:
z = x.view(-1,5)

In [74]:
z 

tensor([[ 2.0778,  0.4181,  3.0650,  1.4837,  2.3440],
        [ 0.8982,  0.6643, -0.8515,  0.5587, -1.1137],
        [ 0.4890, -0.4901, -1.3639,  0.3837,  1.1912]])

In [75]:
x.shape

torch.Size([5, 3])

In [76]:
y.shape

torch.Size([15])

In [77]:
z.shape

torch.Size([3, 5])

In [78]:
# view()返回新的size 但是 是共享 data 的 改变其中一个另外一个也跟着改变
x += 1

In [79]:
x

tensor([[ 3.0778,  1.4181,  4.0650],
        [ 2.4837,  3.3440,  1.8982],
        [ 1.6643,  0.1485,  1.5587],
        [-0.1137,  1.4890,  0.5099],
        [-0.3639,  1.3837,  2.1912]])

In [80]:
y

tensor([ 3.0778,  1.4181,  4.0650,  2.4837,  3.3440,  1.8982,  1.6643,  0.1485,
         1.5587, -0.1137,  1.4890,  0.5099, -0.3639,  1.3837,  2.1912])

In [81]:
z

tensor([[ 3.0778,  1.4181,  4.0650,  2.4837,  3.3440],
        [ 1.8982,  1.6643,  0.1485,  1.5587, -0.1137],
        [ 1.4890,  0.5099, -0.3639,  1.3837,  2.1912]])

In [82]:
#不变量共享 先用clone 创建一个副本然后在使用view
x_cp = x.clone().view(15)

In [83]:
x_cp

tensor([ 3.0778,  1.4181,  4.0650,  2.4837,  3.3440,  1.8982,  1.6643,  0.1485,
         1.5587, -0.1137,  1.4890,  0.5099, -0.3639,  1.3837,  2.1912])

In [84]:
x +=1

In [85]:
x

tensor([[4.0778, 2.4181, 5.0650],
        [3.4837, 4.3440, 2.8982],
        [2.6643, 1.1485, 2.5587],
        [0.8863, 2.4890, 1.5099],
        [0.6361, 2.3837, 3.1912]])

In [86]:
x_cp

tensor([ 3.0778,  1.4181,  4.0650,  2.4837,  3.3440,  1.8982,  1.6643,  0.1485,
         1.5587, -0.1137,  1.4890,  0.5099, -0.3639,  1.3837,  2.1912])

In [87]:
# item 将Tensor 转成 python number 
x = torch.randn(1)

In [88]:
x

tensor([0.5193])

In [89]:
x.item()

0.5193179845809937

In [90]:
# 线性代数
x_cp

tensor([ 3.0778,  1.4181,  4.0650,  2.4837,  3.3440,  1.8982,  1.6643,  0.1485,
         1.5587, -0.1137,  1.4890,  0.5099, -0.3639,  1.3837,  2.1912])

In [96]:
y_cp = x_cp.view(-1,5)

In [97]:
torch.trace(y_cp)

tensor(4.3782)

In [98]:
y_cp

tensor([[ 3.0778,  1.4181,  4.0650,  2.4837,  3.3440],
        [ 1.8982,  1.6643,  0.1485,  1.5587, -0.1137],
        [ 1.4890,  0.5099, -0.3639,  1.3837,  2.1912]])

In [100]:
n = torch.diag(y_cp)

In [101]:
n.sum()

tensor(4.3782)

In [102]:
y_cp.t_()

tensor([[ 3.0778,  1.8982,  1.4890],
        [ 1.4181,  1.6643,  0.5099],
        [ 4.0650,  0.1485, -0.3639],
        [ 2.4837,  1.5587,  1.3837],
        [ 3.3440, -0.1137,  2.1912]])

### 广播机制

In [103]:
x = torch.arange(1,3).view(1,2)

In [104]:
x

tensor([[1, 2]])

In [105]:
y = torch.arange(1,4).view(3,1)

In [106]:
y

tensor([[1],
        [2],
        [3]])

In [107]:
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

### 运算内存开销

In [ ]:
# 索引操作是不会 开辟新内存，但是 y = x + y 这样的运算会新开内存，然后将
# y指向新内存

In [108]:
x = torch.tensor([1,2])

In [109]:
y = torch.tensor([3,4])

In [110]:
id_before = id(y)

In [111]:
id_before

140237196385744

In [112]:
y = y + x 

In [113]:
id(y) == id_before

False

In [114]:
# 如果想指定结果到原来y的内存，我们可以 使用前面介绍的索引来进行替换操作

In [115]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y[:] = x + y 

In [116]:
id(y) == id_before

True

In [117]:
# 运算符全名函数中的out 参数 或者 自加运算 += 达到 上述效果 

In [118]:
torch.add(x,y,out=y)

tensor([5, 8])

In [119]:
id(y) == id_before

True

### Tensor 和 Numpy 相互转换 

In [121]:
# 容易使用numpy() 和 from_numpy() 将 Tensor 和 Numpy中的数据相互转换
# 但是要注意的是数组之间 共享相同的内存 改变其中一个另外一个也改变

In [122]:
a = torch.ones(5)

In [123]:
a

tensor([1., 1., 1., 1., 1.])

In [124]:
b = a.numpy()

In [125]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [126]:
a +=1 

In [127]:
a

tensor([2., 2., 2., 2., 2.])

In [128]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [129]:
b +=1

In [130]:
b

array([3., 3., 3., 3., 3.], dtype=float32)

In [131]:
a

tensor([3., 3., 3., 3., 3.])

In [132]:
a = np.ones(5)

In [133]:
a

array([1., 1., 1., 1., 1.])

In [134]:
b = torch.from_numpy(a)

In [135]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [136]:
a +=1

In [137]:
a

array([2., 2., 2., 2., 2.])

In [138]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [140]:
# 直接用 torch.tensor()  会进行数据拷贝 返回的tensor 和原来的数据不在进行
# 数据共享
c = torch.tensor(a)

In [141]:
c

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [142]:
a+=1

In [143]:
c

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [144]:
a

array([3., 3., 3., 3., 3.])

In [ ]:
### tensor on GPU

## 自动求梯度

### 概念

In [145]:
# 属性为 requires_grad 设置为True  将追踪其上的所有操作  可以利用链式法则
# 进行梯度传播了 计算完成后 可以调用 。backward()来完成所有的梯度计算
# 此Tensor的梯度累计到.grad属性中

### Tensor

In [146]:
x = torch.ones(2,2,requires_grad=True)

In [147]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [149]:
print(x.grad_fn)

None


In [150]:
y = x + 2

In [151]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [152]:
y.grad_fn

In [153]:
# 直接创建的成为叶子节点，叶子节点对应的grad_fn 是 None

In [154]:
x.is_leaf

True

In [156]:
y.is_leaf

False

In [157]:
z = y * y * 3

In [158]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [159]:
out = z.mean()

In [160]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [161]:
a = torch.randn(2,2)

In [162]:
a

tensor([[-0.0293, -0.8738],
        [ 1.2695,  0.0943]])

In [163]:
a = ((a * 3) / (a - 1))

In [164]:
a

tensor([[ 0.0853,  1.3990],
        [14.1313, -0.3122]])

In [165]:
a.requires_grad

False

In [166]:
a.requires_grad_(True)

tensor([[ 0.0853,  1.3990],
        [14.1313, -0.3122]], requires_grad=True)

In [167]:
b = (a * a).sum()

In [168]:
b

tensor(201.7562, grad_fn=<SumBackward0>)

In [169]:
b.grad_fn

### 梯度

In [170]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [171]:
out.backward()

In [172]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [173]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [175]:
# grad 在反向传播过程中是累加的，这意味 这 没运行一次反向传播 梯度都会累加之前
# 之前的梯度，所以一般在反向传播之前需要把 梯度清零

In [176]:
out2 = x.sum()

In [177]:
out2

tensor(4., grad_fn=<SumBackward0>)

In [178]:
out2.backward()

In [179]:
x.grad

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])

In [180]:
out3 = x.sum()

In [181]:
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [182]:
out3.backward()

In [183]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [184]:
x  = torch.tensor([1.,2.,3.,4.],requires_grad=True)

In [185]:
x

tensor([1., 2., 3., 4.], requires_grad=True)

In [186]:
y = x * 2 

In [187]:
y

tensor([2., 4., 6., 8.], grad_fn=<MulBackward0>)

In [188]:
z = y.view(2,2)

In [189]:
z

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)

In [190]:
# z 不是标量 所以在调用 backward 时 需要传入一个和z 同形的权重向量进行加权#
# 求和得到一个标量
v = torch.tensor([[1.,0.1],[0.01,0.001]],dtype=torch.float)

In [191]:
z.backward(v)

In [192]:
x.grad

tensor([2.0000, 0.2000, 0.0200, 0.0020])

In [193]:
# 中断 梯度追踪

In [194]:
x = torch.tensor(1.0,requires_grad=True)

In [195]:
x

tensor(1., requires_grad=True)

In [196]:
y1 = x ** 2

In [197]:
with torch.no_grad():
    y2 = x ** 3 
y3 = y1 + y2 

In [198]:
x.requires_grad

True

In [199]:
y1

tensor(1., grad_fn=<PowBackward0>)

In [200]:
y1.requires_grad

True

In [201]:
y2.requires_grad

False

In [202]:
y3.requires_grad

True

In [203]:
y3.backward()

In [204]:
x.grad

tensor(2.)

In [205]:
# 想要修改 tensor 的数值，但是有不希望被 autograd 记录  需要对tensor.data
# 进行操作

In [206]:
x = torch.ones(1,requires_grad=True)

In [207]:
x

tensor([1.], requires_grad=True)

In [208]:
x.data

tensor([1.])

In [209]:
x.data.requires_grad

False

In [210]:
y = 2 * x

In [211]:
y

tensor([2.], grad_fn=<MulBackward0>)

In [212]:
x.data *= 100

In [213]:
x

tensor([100.], requires_grad=True)

In [214]:
y.backward()

In [215]:
x

tensor([100.], requires_grad=True)

In [216]:
x.grad

tensor([2.])